services:
  loki:
    image: grafana/loki:3.2.0
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - otel-net

networks:
  otel-net:
    external: true