services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.110.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "9987:9987" # OTLP gRPC
      - "55681:55681" # OTLP HTTP
      - "9464:9464" # Prometheus (pull 때문에 필요)
    networks:
      - otel-net

networks:
  otel-net:
    external: true
