receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:9987

  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:

exporters:
  logging:
  # prometheus 사용 하는 경우 활성화
  # prometheus는 pull로 가져 가서 otel-collector의 포트를 열어놔야함.
#  prometheus:
#    endpoint: otel-collector:9464
  # otlp/jaeger:
  #   endpoint: jaeger:4317
  #   tls:
  #     insecure: true # self signed certification 사용시 필수 (ca 검사때문에)
  #     insecure_skip_verify: true

  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  otlp/data-prepper/trace:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true

  otlp/data-prepper/metrics:
    endpoint: data-prepper:21891
    tls:
      insecure: true
      insecure_skip_verify: true

  otlp/data-prepper/logs:
    endpoint: data-prepper:21892
    tls:
      insecure: true
      insecure_skip_verify: true

#  debug:
#    verbosity: detailed
#    sampling_initial: 5
#    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/data-prepper/trace]
    metrics:
      receivers: [otlp]
#      exporters: [logging, prometheus, otlp/data-prepper/metrics] # prometheus 사용 하는 경우 export쪽과 함께 주석해제
      exporters: [debug, otlp/data-prepper/metrics]

    logs:
      receivers: [otlp]
      exporters: [otlp/data-prepper/logs]