services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.60
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "14269:14269"
      - "9411:9411"
      - "4318:4318"
      - "4317:4317" # OTLP gRPC
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HTTP_ENABLED=true
      - COLLECTOR_HTTP_CORSEnabled=true
      - COLLECTOR_HTTP_CORSAllowOrigins=*

    networks:
      - otel-net

networks:
  otel-net:
    external: true
